<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="agent1" nsURI="agent1" nsPrefix="agent1">
  <eClassifiers xsi:type="ecore:EClass" name="AgentMM">
    <eStructuralFeatures xsi:type="ecore:EReference" name="agents" upperBound="-1"
        eType="#//Agent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="agentType" upperBound="-1"
        eType="#//AgentType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Agent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="agentName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="agentValue" upperBound="-1"
        eType="#//AgentAttributeValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgentAttributeValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defines" lowerBound="1"
        upperBound="-1" eType="#//AgentState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" upperBound="-1"
        eType="#//AgentAttribute" eOpposite="#//AgentAttribute/value"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgentState">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stateName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="setDefault" upperBound="-1"
        eType="#//AgentAttributeValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgentType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="agentTypeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="agentAttribute" upperBound="-1"
        eType="#//AgentAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeStates" upperBound="-1"
        eType="#//AgentState" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgentAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="agentAttributeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//AgentAttributeValue" eOpposite="#//AgentAttributeValue/attribute"/>
  </eClassifiers>
</ecore:EPackage>
